apiVersion: fission.io/v1
kind: Environment
metadata:
  name: {{.Values.environment.defaultName}}
  namespace: default
spec:
  poolsize: {{.Values.environment.poolsize}}

  resources:
    limits:
      cpu: {{.Values.environment.cpuMax}}
    requests:
      cpu: {{.Values.environment.cpuMin}}
  runtime:
    image: "{{.Values.environment.image}}:{{.Values.environment.imageVersion}}"
    # lines 16- 20 added for python print show in kubernetes log, 22 - 30 is to mounted path but the volume type is not defined
    container:
      name: {{.Values.environment.defaultName}}
      volumeMounts:
        - name: output
          mountPath: /output
          readOnly: false
    podspec:
      containers:
        - name: {{.Values.environment.defaultName}}
      volumes:
      - name: output
        hostPath:
          path: /tmp
  terminationGracePeriod: {{.Values.environment.gracePeriod}}
  version: {{.Values.environment.version}}