# start with a recent nvidia pytroch image, with rdma and gds lib installed, default python version 3.8, torch 1.10
FROM nvcr.io/nvidia/pytorch:21.09-py3

# install packages and python
RUN apt-get update && \
    apt-get install gcc libev-dev libffi-dev -y && \
    apt-get clean

# update pip to install dependencies
RUN pip3 install --upgrade pip

# Copy the requirements and install
WORKDIR /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt

RUN pip3 install serverlessdl==1.0.1


# Copy the server and start
COPY . /app

# Start a gunicorn server with only one worker to ensure
# isolation on a function basis
# and offer more performance than the default server
#CMD ["gunicorn", "--log-level", "debug", "--access-logfile", "-", "-b", "0.0.0.0:8888", "-t", "2000", "-w 1", "server:app"]

#CMD ["gunicorn", "--log-level", "debug", "-b", "0.0.0.0:8888", "-t", "2000", "-w 1", "server:app"]

#CMD ["gunicorn", "--log-level", "debug", "-b", "0.0.0.0:8888", "-t", "2000", "-w 1", "server:app"]

ENV PYTHONUNBUFFERED 1
ENTRYPOINT ["python"]
CMD ["server.py"]
